"""Stage 08 — assemble outputs/RESULTS_SUMMARY.md, the primary deliverable:
every number real, every gap and caveat stated. No API calls.

Covers the brief's 13 items: dataset counts, cleaning log, retrieval quality,
results pooled + per dataset, statistical tests, observed sample sizes, winners
per budget + graph-arm reading, RQ4, contamination check (LiveRAG vs older
benchmarks), reference conditions with floor-to-ceiling fractions, APT under
both accountings + ranking-change verdict, position ablation, confound checks,
and the explicit failure/substitution list.

Also writes the small committed data sample (data/sample/) the repo layout
promises, and the judge spot-check agreement rate once the human columns in
outputs/judge_spot_check_sample.csv are filled in.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from common import BUDGETS, DATA, MANIFEST_PATH, OUTPUTS, append_log  # noqa: E402

SUMMARY = OUTPUTS / "RESULTS_SUMMARY.md"
PRIMARY_BUDGET = 1000
S = []  # markdown lines


def h(level, text):
    S.append("#" * level + " " + text + "\n")


def p(text=""):
    S.append(text + "\n")


def table(df: pd.DataFrame, max_rows=100):
    if df is None or not len(df):
        p("_not available_")
        return
    S.append(df.head(max_rows).to_markdown(index=False) + "\n")


def load(pathname, reader=pd.read_csv):
    f = Path(pathname)
    return reader(f) if f.exists() else None


def main():
    manifest = json.loads(MANIFEST_PATH.read_text()) if MANIFEST_PATH.exists() else {}
    ev_path = DATA / "eval_records.parquet"
    ev = pd.read_parquet(ev_path) if ev_path.exists() else None
    res = load(OUTPUTS / "preliminary_results.csv")
    res_ds = load(OUTPUTS / "preliminary_results_by_dataset.csv")
    tests = load(OUTPUTS / "stats_tests.csv")
    rq = load(OUTPUTS / "retrieval_quality.csv")
    clean_log = load(OUTPUTS / "data_cleaning_log.csv")
    sizes = load(OUTPUTS / "sample_size_observed.csv")
    pos = load(OUTPUTS / "position_ablation.csv")
    confound = load(OUTPUTS / "graph_confound_checks.csv")
    compliance = load(OUTPUTS / "budget_compliance.csv")
    base_path = DATA / "baseline_records.parquet"
    base = pd.read_parquet(base_path) if base_path.exists() else None

    h(1, "RESULTS SUMMARY — Answer Quality per Token")
    p(f"Generated by src/08_summary.py from pipeline artifacts. Seed {manifest.get('seed')}. "
      f"Generator {manifest.get('generator_model')} (provider pinned: "
      f"{manifest.get('generator_provider_pinned')}), judge {manifest.get('judge_model')}, "
      f"embeddings {manifest.get('embedding_model')}, reranker {manifest.get('rerank_model')}.")
    p("Every number below comes from a file written by a script in this repo. "
      "Sections whose stage has not run say NOT RUN rather than showing anything synthetic.")

    # 1 dataset counts
    h(2, "1. Dataset counts after cleaning")
    s01, s02 = manifest.get("stage01", {}), manifest.get("stage02", {})
    p(f"- Primary questions: {s02.get('questions_primary_clean', 'NOT RUN')} "
      f"(allocation: {s01.get('allocation')})")
    p(f"- Structured questions (RQ4): {s02.get('questions_structured_clean', 'NOT RUN')}")
    p(f"- Corpus: {s02.get('n_passages_clean')} passages -> {s02.get('n_chunks')} chunks "
      f"({s02.get('chunk_tokens')} tokens, {s02.get('chunk_overlap')} overlap, "
      f"min {s02.get('min_chunk_tokens')})")
    p(f"- Tiers that ran: all six datasets loaded iff `failures` empty: "
      f"{s01.get('failures', 'NOT RUN')}")

    h(2, "2. Data cleaning log")
    table(clean_log)

    h(2, "3. Retrieval quality (validated before use)")
    table(rq)
    s03 = manifest.get("stage03", {})
    p(f"HotpotQA dense recall@50 gate (>= 0.7): "
      f"{s03.get('hotpot_dense_recall_at_50', 'NOT RUN')} — passed: {s03.get('gate_passed')}")

    h(2, "4. Results: arm x budget (pooled), and per dataset")
    if res is not None:
        pooled = res[(res.get("hop_type") == "all")]
        table(pooled)
    else:
        p("_NOT RUN — sweep has not executed_")
    h(3, "Per dataset (exploratory: underpowered slices, CIs shown, no significance claims)")
    table(res_ds, max_rows=200)

    h(2, "5. Statistical tests (pre-registered + McNemar, BH-FDR corrected)")
    table(tests, max_rows=200)

    h(2, "6. Observed-effect sample sizes (assumed vs observed)")
    table(sizes)

    h(2, "7. Which arm wins at each budget; where the graph arm helps")
    if res is not None and len(res):
        pooled = res[(res.hop_type == "all") & (res.sweep == "primary")]
        for b in BUDGETS:
            sub = pooled[pooled.budget == b]
            if len(sub):
                w = sub.loc[sub.em.idxmax()]
                p(f"- Budget {b}: **{w['arm']}** EM {w['em']:.3f} "
                  f"[{w.get('em_ci_lo', float('nan')):.3f}, {w.get('em_ci_hi', float('nan')):.3f}]")
        if ev is not None:
            g = ev[(ev.sweep == "primary")]
            graph = g[g.arm == "graph_select"].groupby("hop_type")["em"].mean()
            naive = g[g.arm == "naive_topk"].groupby("hop_type")["em"].mean()
            p(f"- graph_select vs naive_topk by hop type (EM, all budgets): "
              f"multi {graph.get('multi', float('nan')):.3f} vs {naive.get('multi', float('nan')):.3f}; "
              f"single {graph.get('single', float('nan')):.3f} vs {naive.get('single', float('nan')):.3f}")
    else:
        p("_NOT RUN_")

    h(2, "8. RQ4 — structured vs prose")
    if tests is not None:
        table(tests[tests.rq == "RQ4"])
        p("Structured slice source: WikiTableQuestions (separate powered 600-item sweep) "
          "plus content_type tagging of table/code/list chunks inside prose corpora. "
          "Content type is confounded with dataset — stated, not hidden.")
    else:
        p("_NOT RUN_")
    h(3, "RQ4 decomposition: retrieval share vs assembly share of the penalty")
    rq4d = load(OUTPUTS / "rq4_decomposition.csv")
    if rq4d is not None:
        table(rq4d, max_rows=40)
        p("Reading: `gap_total` is the full structured-vs-prose EM penalty; "
          "`gap_assembly_matched_retrieval` recomputes it only on questions whose gold "
          "evidence WAS in the retrieved pool on both sides (retrieval succeeded), so it "
          "isolates assembly+generation; `gap_retrieval_share` is the remainder "
          "attributable to retrieval failure on tables.")
    else:
        p("_not computed_")

    h(2, "9. Contamination check — older benchmarks vs LiveRAG (post-cutoff)")
    cont = load(OUTPUTS / "contamination_check.csv")
    if cont is not None:
        p("At MATCHED retrieval quality (gold_in_pool_only rows, both groups): if older-"
          "benchmark scores stay far above LiveRAG's even when retrieval succeeded "
          "equally, memorization of the older benchmarks is the leading explanation — "
          "capability and retrieval are controlled.")
        table(cont)
    if ev is not None:
        prim = ev[ev.sweep == "primary"]
        old = prim[prim.dataset.isin(["hotpotqa", "squad_v2", "nq_open_gold", "ms_marco"])]
        live = prim[prim.dataset == "liverag"]
        if len(live):
            cmp = pd.DataFrame({
                "metric": ["F1", "faithfulness", "EM (unreliable for LiveRAG: long-form golds)"],
                "older_benchmarks": [old.f1.mean(), old.faithfulness.mean(), old.em.mean()],
                "liverag": [live.f1.mean(), live.faithfulness.mean(), live.em.mean()],
            }).round(4)
            table(cmp)
            p("If older-benchmark scores are implausibly high relative to LiveRAG, memorization "
              "is the suspect explanation; the gap above is the honest measurement of that risk.")
        else:
            p("_LiveRAG rows absent from the sweep_")
    else:
        p("_NOT RUN_")

    h(2, "10. Reference conditions — floor, ceiling, and the cost of the budget")
    if base is not None and ev is not None:
        b = base.groupby("arm")[["em", "f1", "gen_context_tokens"]].mean().round(4)
        table(b.reset_index())
        floor = base[base.arm == "no_context"].em.mean()
        ceil = base[base.arm == "gold_context"].em.mean()
        gap = ceil - floor
        p(f"Floor (no_context) EM = {floor:.3f}; ceiling (gold_context) EM = {ceil:.3f}; "
          f"gap = {gap:.3f}.")
        if gap > 0:
            pooled = ev[ev.sweep == "primary"].groupby("arm")["em"].mean()
            frac = ((pooled - floor) / gap).round(3).sort_values(ascending=False)
            p("Each arm's accuracy as a fraction of the floor-to-ceiling gap (pooled budgets):")
            table(frac.reset_index().rename(columns={"em": "fraction_of_gap"}))
        fc = base[base.arm == "full_context"].em.mean()
        p(f"full_context (no cap) EM = {fc:.3f} — versus the best budgeted arm above: "
          f"this is the direct measurement of what the budget costs (or saves).")
    else:
        p("_NOT RUN (04b)_")

    h(2, "11. APT under both accountings — does the ranking change?")
    if res is not None and "apt_generator_per_1k" in (res.columns if res is not None else []):
        pooled = res[(res.hop_type == "all") & (res.sweep == "primary")]
        rank_gen = pooled.groupby("arm")["apt_generator_per_1k"].mean().rank(ascending=False)
        rank_tot = pooled.groupby("arm")["apt_total_per_1k"].mean().rank(ascending=False)
        cmp = pd.DataFrame({"APT_generator_rank": rank_gen, "APT_total_rank": rank_tot})
        cmp["rank_changed"] = cmp.APT_generator_rank != cmp.APT_total_rank
        table(cmp.reset_index())
        changed = bool(cmp.rank_changed.any())
        p(f"**Ranking changes between accountings: {changed}.** "
          + ("The cheapest-looking strategy is NOT the cheapest strategy — headline finding."
             if changed else "The generator-only metric's bias did not reorder arms here."))
    else:
        p("_NOT RUN_")

    h(2, "12. Position ablation — lost in the middle, measured")
    if pos is not None:
        table(pos)
        s4c = manifest.get("stage04c", {})
        p(f"Arm: {s4c.get('best_arm')}; skips: {s4c.get('skipped_no_assembly', 0)} no assembly, "
          f"{s4c.get('skipped_no_gold_in_selection', 0)} no gold in selection, "
          f"{s4c.get('skipped_over_budget', 0)} BPE jitter.")
    else:
        p("_NOT RUN (04c)_")

    h(2, "13. Graph-arm confound checks")
    if compliance is not None:
        p("Budget parity (realized context tokens per arm — a >5% spread would "
          "manufacture wins):")
        table(compliance)
    table(confound, max_rows=120)
    if tests is not None:
        dedup_rows = tests[tests.comparison.str.contains("naive_topk_dedup", na=False)]
        if len(dedup_rows):
            p("Dedup control (if this closes most of the graph-vs-naive gap, the finding is "
              "'deduplicate your context', not 'graph structure helps'):")
            table(dedup_rows)
        sens_rows = tests[tests.rq == "SENSITIVITY"]
        if len(sens_rows):
            p("Hyperparameter sensitivity (hops=1 vs hops=2):")
            table(sens_rows)

    h(2, "Practitioner decision guide (preliminary)")
    if ev is not None and len(ev):
        segs = []
        prim_ok = ev[(ev.sweep == "primary")]
        for seg_name, g in [("pooled prose", prim_ok),
                            ("multi-hop", prim_ok[prim_ok.hop_type == "multi"]),
                            ("single-hop", prim_ok[prim_ok.hop_type == "single"]),
                            ("structured/tables", ev[ev.sweep == "structured"])]:
            for b in sorted(g.budget.unique()):
                gb = g[g.budget == b]
                by = gb.groupby("arm")["em"].mean()
                if not len(by):
                    continue
                best = by.idxmax()
                second = by.drop(best).max() if len(by) > 1 else float("nan")
                segs.append(dict(segment=seg_name, budget=b, best_arm=best,
                                 best_em=round(by.max(), 3),
                                 margin_over_second=round(by.max() - second, 3)))
        table(pd.DataFrame(segs), max_rows=40)
        p("Caveats the guide inherits (stated wherever it is quoted): the RQ1 margin is "
          "small and not significant at the pre-registered budget — 'best' rows with a "
          "margin under ~0.02 EM should be read as 'tied with naive top-k'; returns to "
          "budget are strongly diminishing, so the cheapest budget meeting the accuracy "
          "need is usually the right choice; graph_select and compress_llmlingua are "
          "dominated at every budget in this configuration.")
    else:
        p("_NOT RUN_")

    h(2, "Judge spot-check (Synopsis-promised hand verification)")
    spot = load(OUTPUTS / "judge_spot_check_sample.csv")
    if spot is not None and "human_agrees" in spot.columns:
        done = spot[spot.human_agrees.astype(str).str.strip().isin(["yes", "no"])]
        if len(done):
            rate = (done.human_agrees.astype(str).str.strip() == "yes").mean()
            p(f"Human-judge agreement: {rate:.0%} on {len(done)} hand-verified judgements.")
        else:
            p(f"Sample of {len(spot)} judgements written to judge_spot_check_sample.csv — "
              f"**human verification pending** (fill human_faithfulness / human_agrees).")
    else:
        p("_NOT RUN_")

    h(2, "Failures, skips, and substitutions (complete list)")
    for d in manifest.get("deviations", []) or ["(none recorded)"]:
        p(f"- {d}")
    p("- Known method caveats (disclosed by design): LLMLingua-2 compression is "
      "question-agnostic (the published method); LiveRAG gold answers are long-form so its "
      "EM is unreliable (F1/faithfulness used); RQ4 is unpaired and content type is "
      "confounded with dataset; RQ1's 'best arm' is max-selected on the test data "
      "(winner's-curse caveat attached to its p-values); per-dataset splits are "
      "exploratory; MultiHop-RAG evaluation questions come from its only published split "
      "(train); pgvector persists vectors while query-time retrieval uses exact cosine "
      "over the same vectors (removes ANN variance).")
    p("- Token-accounting convention for APT_total: RECOMP's extractive pass and the "
      "LLMLingua fallback (when active) are lexical, not model reads — their candidate-"
      "pool charge is the as-published-method imputation, applied so RECOMP/LLMLingua "
      "are accounted like the published pipelines they stand in for. The two-proportion "
      "z rows pair a pre-registered UNPAIRED p with a PAIRED bootstrap CI (both mandated); "
      "where they disagree, McNemar carries the paired inference.")

    SUMMARY.write_text("".join(S))
    print(f"[08] wrote {SUMMARY} ({len(S)} blocks)")

    # small committed sample (repo layout: data/ gitignored EXCEPT data/sample/)
    sample_dir = DATA / "sample"
    sample_dir.mkdir(exist_ok=True)
    qp = DATA / "questions_primary_clean.parquet"
    if qp.exists():
        pd.read_parquet(qp).head(20).to_csv(sample_dir / "questions_primary_sample.csv", index=False)
    cc = DATA / "corpus_chunks.parquet"
    if cc.exists():
        pd.read_parquet(cc).head(20).to_csv(sample_dir / "corpus_chunks_sample.csv", index=False)
    append_log("Stage 08 summary", f"RESULTS_SUMMARY.md regenerated "
               f"({'with' if ev is not None else 'WITHOUT'} sweep records).")


if __name__ == "__main__":
    main()
